name: Hello World Composite Action

on:
  push:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello, ${{ env.who-to-greet }}!"
    - name: Generate random number
      id: random-number
      run: echo "::set-output name=random-number::$RANDOM"