name: 'Tier Comparison'
description: 'Run Tier Comparison SheetShuttle plugin'
runs:
  using: "composite"
  steps:
    - run: python ReadWriteGoogleSheet.py
      shell: bash
    - run: python plugins/github_issues.py
      shell: bash
