name: 'Tier Comparison'
description: 'Run Tier Comparison SheetShuttle plugin'
runs:
  using: "composite"
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.9'
  - name: Connect to Sheet
    shell: bash
    run: python ${{github.action_path}}/ReadWriteGoogleSheet.py
  - name: File issue(s)
    shell: bash
    run: python ${{github.action_path}}plugins/github_issues.py
