'<br># Create an issue<br># labels are optional<br>- type: issue<br>  action: create<br>  repo:
  CMPSC-203-Allegheny-College-Fall-2022/Tier-comparison<br>  title: Green Tier<br>  body:
  This is the green tier. You are doing great!<br>  labels:<br>    - SheetShuttle<br>    -
  Automated<br>'
