---
# Create an issue
# labels are optional
  - type: issue
    action: create
    repo: allegheny-college-sandbox/Tier-tester
    title: Green Tier
    body: "## Green Tier\nCongratulations, you are in the Green Tier! You are doing\
      \ great and keeping up with the course material. Keep up the good work!\n###\
      \ What&#x27;s Working Well?\n- List the things you are doing well in the course\n\
      ### What Could Be Improved?\n- List the areas where you think you could improve\
      \ or need more practice\n### Action Plan\n- Create an action plan to address\
      \ the areas that need improvement - Schedule time to work on your action plan\
      \ and monitor your progress "
    labels:
      - SheetShuttle
      - Automated
...
